### ISSUE TITLE
Ergänze Metafacture als ETL-Tool

### ISSUE THREAD

**Issue by TobiasNx** [pro4bib/pica#15]
Metafacture könnte als open source ETL-Tool ergänzt werden, das in der Lage ist. PICA-Daten zu verarbeiten. 

https://github.com/metafacture/metafacture-core

**Comment by nichtich** [comment]
[So](https://github.com/pro4bib/pica/commit/e55a958bc78c2aa7977a184614bc3f76311d9fe5)?

**Comment by TobiasNx** [comment]
ja, danke :+1:
